namespace TTGJ.Audio
{
    public enum AudioType
    {
        Waterfall_Sound = 1,
        Teleportation_Gate = 2,
        Water_Spray_Sound = 3,
        Kettle_Watering_Sound = 4,
        Popcorn_Machine_Sound_1 = 5,
        Popcorn_Machine_Dispensing = 6,
        Popcorn_Machine_Loading_Crops = 7,
        Key_Door_Opening_Closing_Sound = 8,
        Magic_Sound_Effect = 9,
        Beet = 10,
        Sheep_Bleat = 11,
        Q_Bouncy_Crop = 12,
        Character_Planting_Plant = 13,
        Crop_Falling_to_Ground = 14,
        Bowling_Pin_Falling_Sound = 15,
        Bowling_Ball_Rolling_Sound = 16,
        Bowling_Ball_Collision_Sound = 17,
        Pumpkin_Swallowing = 18,
        Billiard_Ball_Collision_2 = 19,
        Billiard_Ball_Pocketing_Sound = 20,
        Potato_Splitting = 21,
        Giant_Crop_Falling_to_Ground = 22,
        Harvesting_Strange_Crop_2 = 23,
        Harvesting_Regular_Crop = 24,
        Water_Beet_Falling_to_Ground = 25,
        Bush_Swaying = 26,
        Item_Falling_into_Water_Sound = 27,
        Character_Discarding_Item = 28,
        Character_Lifting_Item = 29,
        Character_Landing_after_Falling_from_Sky = 30,
        Character_Eating_Food = 31,
        Character_Picking_up_Item = 32,
        Character_Walking_Wooden_Bridge = 33,
        Character_Walking_Sand_Soil = 34,
        Character_Walking_Beach = 35,
        Character_Walking_Lotus_Leaf_Path = 36,
        Character_Walking_Default = 37,
        Eat_Popcorn = 38,
        Button_Click = 39,
        Mouse_Focus_1 = 40,


    }
}