
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Config
{
public sealed partial class ItemDetail : Luban.BeanBase
{
    public ItemDetail(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
    }

    public static ItemDetail DeserializeItemDetail(JSONNode _buf)
    {
        return new Config.ItemDetail(_buf);
    }

    /// <summary>
    /// 物品Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名字
    /// </summary>
    public readonly string Name;
    public readonly string Icon;
    /// <summary>
    /// 物品描述
    /// </summary>
    public readonly string Des;
   
    public const int __ID__ = 105521008;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "des:" + Des + ","
        + "}";
    }
}
}

