
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Config
{
public sealed partial class ShopDetail : Luban.BeanBase
{
    public ShopDetail(JSONNode _buf) 
    {
        { if(!_buf["ShopID"].IsNumber) { throw new SerializationException(); }  ShopID = _buf["ShopID"]; }
        { if(!_buf["ItemID"].IsNumber) { throw new SerializationException(); }  ItemID = _buf["ItemID"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
    }

    public static ShopDetail DeserializeShopDetail(JSONNode _buf)
    {
        return new Config.ShopDetail(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int ShopID;
    public readonly int ItemID;
    /// <summary>
    /// 商品的价格
    /// </summary>
    public readonly float Price;
   
    public const int __ID__ = 1265748243;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ShopID:" + ShopID + ","
        + "ItemID:" + ItemID + ","
        + "price:" + Price + ","
        + "}";
    }
}
}

