
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Config
{
public partial class Shop
{
    private readonly System.Collections.Generic.Dictionary<int, Config.ShopDetail> _dataMap;
    private readonly System.Collections.Generic.List<Config.ShopDetail> _dataList;
    
    public Shop(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Config.ShopDetail>(count);
        _dataList = new System.Collections.Generic.List<Config.ShopDetail>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Config.ShopDetail _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Config.ShopDetail.DeserializeShopDetail(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ShopID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Config.ShopDetail> DataMap => _dataMap;
    public System.Collections.Generic.List<Config.ShopDetail> DataList => _dataList;

    public Config.ShopDetail GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Config.ShopDetail Get(int key) => _dataMap[key];
    public Config.ShopDetail this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

