//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Settings/InputSystem/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d6c165b6-3f63-4b80-bb94-ff2e67f74c21"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ca0f1d3d-dcf1-47d0-87a6-4491fada9793"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Operate"",
                    ""type"": ""Button"",
                    ""id"": ""03a0da99-9db1-4a03-897d-01fdb65852d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelOperate"",
                    ""type"": ""Button"",
                    ""id"": ""c2132d99-a92a-4e37-ba37-253f9c7f3a34"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0152d43a-edf3-49dd-b1ca-b6dee326fbf0"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""081970db-87b9-4003-806a-8e339cb0281e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0df62efe-cf4d-40f9-b538-9f877433728f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8f89a828-208e-48ee-a44d-e4f3206ab098"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1a0b575c-630d-4268-8243-354f8ebc0b0a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6e84756f-90c4-48c9-8c35-e77fd493914f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ca68bce8-9404-430d-b554-159100ef61e2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Operate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac3a09db-a016-4013-a0de-a6ac47db199f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelOperate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Airship"",
            ""id"": ""09593261-d3fe-478d-8852-0d1467775310"",
            ""actions"": [
                {
                    ""name"": ""FlyHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""3f7816db-822b-4660-a4ad-cfd75248cb45"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FlyRise"",
                    ""type"": ""Button"",
                    ""id"": ""5c3a269c-add2-4884-83b3-2c3ba90ee042"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlyFall"",
                    ""type"": ""Button"",
                    ""id"": ""1cb1c9e7-9ee2-4632-a3a5-a68bc0126e96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelOperate"",
                    ""type"": ""Button"",
                    ""id"": ""48c24f88-9f7f-452d-954e-c705d9b401e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""26a59e6e-224e-4dd4-80ba-f914821357f9"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""861ba700-adea-4358-8ca0-c6036559d9fe"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyRise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22fa309a-e08a-44b2-9bd0-7e72de758f38"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyFall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d461ee50-d8db-48ac-8b50-f76cdd979846"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelOperate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""0464424a-5cfd-4503-a27c-e8c709a80b5a"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Operate = m_Player.FindAction("Operate", throwIfNotFound: true);
        m_Player_CancelOperate = m_Player.FindAction("CancelOperate", throwIfNotFound: true);
        // Airship
        m_Airship = asset.FindActionMap("Airship", throwIfNotFound: true);
        m_Airship_FlyHorizontal = m_Airship.FindAction("FlyHorizontal", throwIfNotFound: true);
        m_Airship_FlyRise = m_Airship.FindAction("FlyRise", throwIfNotFound: true);
        m_Airship_FlyFall = m_Airship.FindAction("FlyFall", throwIfNotFound: true);
        m_Airship_CancelOperate = m_Airship.FindAction("CancelOperate", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
    }

    ~@InputController()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputController.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Airship.enabled, "This will cause a leak and performance issues, InputController.Airship.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, InputController.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Operate;
    private readonly InputAction m_Player_CancelOperate;
    public struct PlayerActions
    {
        private @InputController m_Wrapper;
        public PlayerActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Operate => m_Wrapper.m_Player_Operate;
        public InputAction @CancelOperate => m_Wrapper.m_Player_CancelOperate;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Operate.started += instance.OnOperate;
            @Operate.performed += instance.OnOperate;
            @Operate.canceled += instance.OnOperate;
            @CancelOperate.started += instance.OnCancelOperate;
            @CancelOperate.performed += instance.OnCancelOperate;
            @CancelOperate.canceled += instance.OnCancelOperate;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Operate.started -= instance.OnOperate;
            @Operate.performed -= instance.OnOperate;
            @Operate.canceled -= instance.OnOperate;
            @CancelOperate.started -= instance.OnCancelOperate;
            @CancelOperate.performed -= instance.OnCancelOperate;
            @CancelOperate.canceled -= instance.OnCancelOperate;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Airship
    private readonly InputActionMap m_Airship;
    private List<IAirshipActions> m_AirshipActionsCallbackInterfaces = new List<IAirshipActions>();
    private readonly InputAction m_Airship_FlyHorizontal;
    private readonly InputAction m_Airship_FlyRise;
    private readonly InputAction m_Airship_FlyFall;
    private readonly InputAction m_Airship_CancelOperate;
    public struct AirshipActions
    {
        private @InputController m_Wrapper;
        public AirshipActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @FlyHorizontal => m_Wrapper.m_Airship_FlyHorizontal;
        public InputAction @FlyRise => m_Wrapper.m_Airship_FlyRise;
        public InputAction @FlyFall => m_Wrapper.m_Airship_FlyFall;
        public InputAction @CancelOperate => m_Wrapper.m_Airship_CancelOperate;
        public InputActionMap Get() { return m_Wrapper.m_Airship; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AirshipActions set) { return set.Get(); }
        public void AddCallbacks(IAirshipActions instance)
        {
            if (instance == null || m_Wrapper.m_AirshipActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AirshipActionsCallbackInterfaces.Add(instance);
            @FlyHorizontal.started += instance.OnFlyHorizontal;
            @FlyHorizontal.performed += instance.OnFlyHorizontal;
            @FlyHorizontal.canceled += instance.OnFlyHorizontal;
            @FlyRise.started += instance.OnFlyRise;
            @FlyRise.performed += instance.OnFlyRise;
            @FlyRise.canceled += instance.OnFlyRise;
            @FlyFall.started += instance.OnFlyFall;
            @FlyFall.performed += instance.OnFlyFall;
            @FlyFall.canceled += instance.OnFlyFall;
            @CancelOperate.started += instance.OnCancelOperate;
            @CancelOperate.performed += instance.OnCancelOperate;
            @CancelOperate.canceled += instance.OnCancelOperate;
        }

        private void UnregisterCallbacks(IAirshipActions instance)
        {
            @FlyHorizontal.started -= instance.OnFlyHorizontal;
            @FlyHorizontal.performed -= instance.OnFlyHorizontal;
            @FlyHorizontal.canceled -= instance.OnFlyHorizontal;
            @FlyRise.started -= instance.OnFlyRise;
            @FlyRise.performed -= instance.OnFlyRise;
            @FlyRise.canceled -= instance.OnFlyRise;
            @FlyFall.started -= instance.OnFlyFall;
            @FlyFall.performed -= instance.OnFlyFall;
            @FlyFall.canceled -= instance.OnFlyFall;
            @CancelOperate.started -= instance.OnCancelOperate;
            @CancelOperate.performed -= instance.OnCancelOperate;
            @CancelOperate.canceled -= instance.OnCancelOperate;
        }

        public void RemoveCallbacks(IAirshipActions instance)
        {
            if (m_Wrapper.m_AirshipActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAirshipActions instance)
        {
            foreach (var item in m_Wrapper.m_AirshipActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AirshipActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AirshipActions @Airship => new AirshipActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    public struct UIActions
    {
        private @InputController m_Wrapper;
        public UIActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnOperate(InputAction.CallbackContext context);
        void OnCancelOperate(InputAction.CallbackContext context);
    }
    public interface IAirshipActions
    {
        void OnFlyHorizontal(InputAction.CallbackContext context);
        void OnFlyRise(InputAction.CallbackContext context);
        void OnFlyFall(InputAction.CallbackContext context);
        void OnCancelOperate(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
    }
}
