
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.test
{
public sealed partial class TestDefineDetail : Luban.BeanBase
{
    public TestDefineDetail(JSONNode _buf) 
    {
        { if(!_buf["ItemName"].IsString) { throw new SerializationException(); }  ItemName = _buf["ItemName"]; }
        { if(!_buf["ItemDescription"].IsString) { throw new SerializationException(); }  ItemDescription = _buf["ItemDescription"]; }
    }

    public static TestDefineDetail DeserializeTestDefineDetail(JSONNode _buf)
    {
        return new test.TestDefineDetail(_buf);
    }

    /// <summary>
    /// 道具名字
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string ItemDescription;
   
    public const int __ID__ = -135918182;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemName:" + ItemName + ","
        + "ItemDescription:" + ItemDescription + ","
        + "}";
    }
}
}

