
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class audio : Luban.BeanBase
{
    public audio(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["soundTip"].IsString) { throw new SerializationException(); }  SoundTip = _buf["soundTip"]; }
        { if(!_buf["soundType"].IsNumber) { throw new SerializationException(); }  SoundType = _buf["soundType"]; }
        { var __json0 = _buf["assetPath"]; if(!__json0.IsArray) { throw new SerializationException(); } AssetPath = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  AssetPath.Add(__v0); }   }
    }

    public static audio Deserializeaudio(JSONNode _buf)
    {
        return new audio(_buf);
    }

    /// <summary>
    /// 音效id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 音效名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 音效描述
    /// </summary>
    public readonly string SoundTip;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int SoundType;
    /// <summary>
    /// 文件路径
    /// </summary>
    public readonly System.Collections.Generic.List<string> AssetPath;
   
    public const int __ID__ = 93166550;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "soundTip:" + SoundTip + ","
        + "soundType:" + SoundType + ","
        + "assetPath:" + Luban.StringUtil.CollectionToString(AssetPath) + ","
        + "}";
    }
}
}

