
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 场景内是否可以碰撞
    /// </summary>
    public enum collision
    {
        /// <summary>
        /// 可以碰撞
        /// </summary>
        collision_true = 0,
        /// <summary>
        /// 不可以碰撞
        /// </summary>
        collision_false = 1,
    }

} 

