
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否可以染色
    /// </summary>
    public enum drawing
    {
        /// <summary>
        /// 可以染色
        /// </summary>
        drawing_true = 0,
        /// <summary>
        /// 不可以染色
        /// </summary>
        drawing_false = 1,
    }

} 

