
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 宝可梦升级速度
    /// </summary>
    public enum experience_growth
    {
        /// <summary>
        /// 最快,初期升级非常快，但后期所需经验值大幅增加。
        /// </summary>
        ​​Erratic​​ = 0,
        /// <summary>
        /// 快,整体升级速度较快，达到100级所需的总经验值相对较少。
        /// </summary>
        ​​Fast​​ = 1,
        /// <summary>
        /// 较快,升级所需经验值呈平稳的抛物线增长，是最常见的类型之一。
        /// </summary>
        ​​Medium Fast​​ = 2,
        /// <summary>
        /// 较慢,升级曲线较为复杂，前期和中期升级速度适中。
        /// </summary>
        ​​Medium Slow​​ = 3,
        /// <summary>
        /// 慢,整体升级速度较慢，需要积累较多的经验值才能升级。
        /// </summary>
        ​​Slow​​ = 4,
        /// <summary>
        /// 最慢,初期升级极慢，但从中期开始升级速度会显著加快
        /// </summary>
        ​​Fluctuating​​ = 5,
    }

} 

