
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class global : Luban.BeanBase
{
    public global(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["effect"].IsString) { throw new SerializationException(); }  Effect = _buf["effect"]; }
        { if(!_buf["tips"].IsString) { throw new SerializationException(); }  Tips = _buf["tips"]; }
    }

    public static global Deserializeglobal(JSONNode _buf)
    {
        return new global(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 杂项名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Tips;
   
    public const int __ID__ = -1243020381;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "effect:" + Effect + ","
        + "tips:" + Tips + ","
        + "}";
    }
}
}

