
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class house : Luban.BeanBase
{
    public house(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["cropList"]; if(!__json0.IsArray) { throw new SerializationException(); } CropList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CropList.Add(__v0); }   }
    }

    public static house Deserializehouse(JSONNode _buf)
    {
        return new house(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 配方名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 作物ID#作物ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> CropList;
   
    public const int __ID__ = 99469088;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "cropList:" + Luban.StringUtil.CollectionToString(CropList) + ","
        + "}";
    }
}
}

