
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否可以被门吞
    /// </summary>
    public enum if_door
    {
        /// <summary>
        /// 可以被门吞
        /// </summary>
        door_true = 0,
        /// <summary>
        /// 不可以被门吞
        /// </summary>
        door_false = 1,
    }

} 

