
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 吞下有无效果
    /// </summary>
    public enum if_eat
    {
        /// <summary>
        /// 吞下无效果
        /// </summary>
        eat_true = 0,
        /// <summary>
        /// 吞下有效果
        /// </summary>
        eat_false = 1,
    }

} 

