
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否会被隐藏门吃
    /// </summary>
    public enum if_hidden_door
    {
        /// <summary>
        /// 可以被隐藏门吃
        /// </summary>
        hidden_door_true = 0,
        /// <summary>
        /// 不可以被隐藏门吃
        /// </summary>
        hidden_door_false = 1,
    }

} 

