
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否为隐藏物品
    /// </summary>
    public enum if_hide
    {
        /// <summary>
        /// 是隐藏物品
        /// </summary>
        hide_true = 0,
        /// <summary>
        /// 不是隐藏物品
        /// </summary>
        hide_false = 1,
    }

} 

