
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否会被湖神吃
    /// </summary>
    public enum if_lake
    {
        /// <summary>
        /// 可以被湖神吃
        /// </summary>
        ake_true = 0,
        /// <summary>
        /// 不可以被湖神吃
        /// </summary>
        ake_false = 1,
    }

} 

