
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否可以被南瓜吞
    /// </summary>
    public enum if_pumpkin
    {
        /// <summary>
        /// 可以被南瓜吞
        /// </summary>
        pumpkin_true = 0,
        /// <summary>
        /// 不可以南瓜吞
        /// </summary>
        pumpkin_false = 1,
    }

} 

