
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否会被爆米花机吃
    /// </summary>
    public enum if_popcorn
    {
        /// <summary>
        /// 可以被爆米花机吃
        /// </summary>
        popcorn_true = 0,
        /// <summary>
        /// 不可以被爆米花机吃
        /// </summary>
        popcorn_false = 1,
    }

} 

