
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemCombine : Luban.BeanBase
{
    public ItemCombine(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["costMainBuckets_1"].IsNumber) { throw new SerializationException(); }  CostMainBuckets1 = _buf["costMainBuckets_1"]; }
        { if(!_buf["costMainBuckets_2"].IsNumber) { throw new SerializationException(); }  CostMainBuckets2 = _buf["costMainBuckets_2"]; }
        { if(!_buf["rewardBoxId"].IsNumber) { throw new SerializationException(); }  RewardBoxId = _buf["rewardBoxId"]; }
        { if(!_buf["sound"].IsString) { throw new SerializationException(); }  Sound = _buf["sound"]; }
    }

    public static ItemCombine DeserializeItemCombine(JSONNode _buf)
    {
        return new ItemCombine(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 配方名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 材料1
    /// </summary>
    public readonly int CostMainBuckets1;
    /// <summary>
    /// 材料2
    /// </summary>
    public readonly int CostMainBuckets2;
    /// <summary>
    /// 合成道具id
    /// </summary>
    public readonly int RewardBoxId;
    /// <summary>
    /// 合成音效
    /// </summary>
    public readonly string Sound;
   
    public const int __ID__ = 2084025996;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "costMainBuckets1:" + CostMainBuckets1 + ","
        + "costMainBuckets2:" + CostMainBuckets2 + ","
        + "rewardBoxId:" + RewardBoxId + ","
        + "sound:" + Sound + ","
        + "}";
    }
}
}

