
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemNew : Luban.BeanBase
{
    public ItemNew(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["itemTips"].IsString) { throw new SerializationException(); }  ItemTips = _buf["itemTips"]; }
        { if(!_buf["itemType"].IsNumber) { throw new SerializationException(); }  ItemType = _buf["itemType"]; }
        { if(!_buf["model"].IsString) { throw new SerializationException(); }  Model = _buf["model"]; }
        { if(!_buf["model_size"].IsNumber) { throw new SerializationException(); }  ModelSize = _buf["model_size"]; }
        { if(!_buf["evo_id"].IsNumber) { throw new SerializationException(); }  EvoId = _buf["evo_id"]; }
        { if(!_buf["drawing"].IsNumber) { throw new SerializationException(); }  Drawing = _buf["drawing"]; }
        { if(!_buf["collision"].IsNumber) { throw new SerializationException(); }  Collision = _buf["collision"]; }
        { if(!_buf["lift"].IsNumber) { throw new SerializationException(); }  Lift = _buf["lift"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
        { if(!_buf["if_door"].IsNumber) { throw new SerializationException(); }  IfDoor = _buf["if_door"]; }
        { if(!_buf["if_pumpkin"].IsNumber) { throw new SerializationException(); }  IfPumpkin = _buf["if_pumpkin"]; }
        { if(!_buf["if_hide"].IsNumber) { throw new SerializationException(); }  IfHide = _buf["if_hide"]; }
        { if(!_buf["sound_collision"].IsString) { throw new SerializationException(); }  SoundCollision = _buf["sound_collision"]; }
        { if(!_buf["sound_floor"].IsString) { throw new SerializationException(); }  SoundFloor = _buf["sound_floor"]; }
        { if(!_buf["collision_Effect"].IsString) { throw new SerializationException(); }  CollisionEffect = _buf["collision_Effect"]; }
        { if(!_buf["buffid"].IsString) { throw new SerializationException(); }  Buffid = _buf["buffid"]; }
        { if(!_buf["maturity_Effect"].IsString) { throw new SerializationException(); }  MaturityEffect = _buf["maturity_Effect"]; }
        { if(!_buf["if_eat"].IsNumber) { throw new SerializationException(); }  IfEat = _buf["if_eat"]; }
        { if(!_buf["eat_Effect"].IsString) { throw new SerializationException(); }  EatEffect = _buf["eat_Effect"]; }
    }

    public static ItemNew DeserializeItemNew(JSONNode _buf)
    {
        return new ItemNew(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string ItemTips;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 道具模型
    /// </summary>
    public readonly string Model;
    /// <summary>
    /// 道具模型大小
    /// </summary>
    public readonly float ModelSize;
    /// <summary>
    /// 进化id
    /// </summary>
    public readonly int EvoId;
    /// <summary>
    /// 是否看染色
    /// </summary>
    public readonly int Drawing;
    /// <summary>
    /// 场景内（收获后）碰撞
    /// </summary>
    public readonly int Collision;
    /// <summary>
    /// 是否可以举起
    /// </summary>
    public readonly int Lift;
    /// <summary>
    /// 物品举高时的高度
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 是否可以被门吞
    /// </summary>
    public readonly int IfDoor;
    /// <summary>
    /// 是否可以被南瓜吞
    /// </summary>
    public readonly int IfPumpkin;
    /// <summary>
    /// 是否为隐藏物品
    /// </summary>
    public readonly int IfHide;
    /// <summary>
    /// 场景内碰撞音效
    /// </summary>
    public readonly string SoundCollision;
    /// <summary>
    /// 和地面碰撞音效
    /// </summary>
    public readonly string SoundFloor;
    /// <summary>
    /// 场景内碰撞效果
    /// </summary>
    public readonly string CollisionEffect;
    /// <summary>
    /// buffid
    /// </summary>
    public readonly string Buffid;
    /// <summary>
    /// 作物成熟时效果
    /// </summary>
    public readonly string MaturityEffect;
    /// <summary>
    /// 吞下是否有效果
    /// </summary>
    public readonly int IfEat;
    /// <summary>
    /// 吞下时效果
    /// </summary>
    public readonly string EatEffect;
   
    public const int __ID__ = -514125459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "itemTips:" + ItemTips + ","
        + "itemType:" + ItemType + ","
        + "model:" + Model + ","
        + "modelSize:" + ModelSize + ","
        + "evoId:" + EvoId + ","
        + "drawing:" + Drawing + ","
        + "collision:" + Collision + ","
        + "lift:" + Lift + ","
        + "height:" + Height + ","
        + "ifDoor:" + IfDoor + ","
        + "ifPumpkin:" + IfPumpkin + ","
        + "ifHide:" + IfHide + ","
        + "soundCollision:" + SoundCollision + ","
        + "soundFloor:" + SoundFloor + ","
        + "collisionEffect:" + CollisionEffect + ","
        + "buffid:" + Buffid + ","
        + "maturityEffect:" + MaturityEffect + ","
        + "ifEat:" + IfEat + ","
        + "eatEffect:" + EatEffect + ","
        + "}";
    }
}
}

