
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum itemType
    {
        /// <summary>
        /// 种子袋
        /// </summary>
        seed_bag = 0,
        /// <summary>
        /// 作物
        /// </summary>
        crop = 1,
        /// <summary>
        /// 巨大作物
        /// </summary>
        big_crop = 2,
        /// <summary>
        /// 迷你作物
        /// </summary>
        mini_crop = 3,
        /// <summary>
        /// 基础物品
        /// </summary>
        basic_items = 4,
        /// <summary>
        /// 特殊
        /// </summary>
        special = 5,
        /// <summary>
        /// 房子
        /// </summary>
        house = 6,
        /// <summary>
        /// npc
        /// </summary>
        npc = 7,
        /// <summary>
        /// 幼苗
        /// </summary>
        seeding = 8,
    }

} 

