
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 是否可以举起
    /// </summary>
    public enum lift
    {
        /// <summary>
        /// 可以举起
        /// </summary>
        lift_true = 0,
        /// <summary>
        /// 不可以举起
        /// </summary>
        lift_false = 1,
    }

} 

