
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class map : Luban.BeanBase
{
    public map(JSONNode _buf) 
    {
        { if(!_buf["mapId"].IsNumber) { throw new SerializationException(); }  MapId = _buf["mapId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["mapBackground"].IsString) { throw new SerializationException(); }  MapBackground = _buf["mapBackground"]; }
        { var __json0 = _buf["nextId"]; if(!__json0.IsArray) { throw new SerializationException(); } NextId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NextId.Add(__v0); }   }
        { var __json0 = _buf["pokemon"]; if(!__json0.IsArray) { throw new SerializationException(); } Pokemon = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Pokemon.Add(__v0); }   }
        { var __json0 = _buf["pokemon_Boss"]; if(!__json0.IsArray) { throw new SerializationException(); } PokemonBoss = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PokemonBoss.Add(__v0); }   }
    }

    public static map Deserializemap(JSONNode _buf)
    {
        return new map(_buf);
    }

    /// <summary>
    /// 地图id
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// 地图名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 地图背景
    /// </summary>
    public readonly string MapBackground;
    /// <summary>
    /// 下一个地图
    /// </summary>
    public readonly System.Collections.Generic.List<int> NextId;
    /// <summary>
    /// 可以生成的精灵
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pokemon;
    /// <summary>
    /// 可以生成的boss
    /// </summary>
    public readonly System.Collections.Generic.List<int> PokemonBoss;
   
    public const int __ID__ = 107868;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "mapId:" + MapId + ","
        + "name:" + Name + ","
        + "mapBackground:" + MapBackground + ","
        + "nextId:" + Luban.StringUtil.CollectionToString(NextId) + ","
        + "pokemon:" + Luban.StringUtil.CollectionToString(Pokemon) + ","
        + "pokemonBoss:" + Luban.StringUtil.CollectionToString(PokemonBoss) + ","
        + "}";
    }
}
}

