
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 副本子类型
    /// </summary>
    public enum map_SubType
    {
        /// <summary>
        /// 简单宝可梦
        /// </summary>
        pokemon = 0,
        /// <summary>
        /// boss宝可梦
        /// </summary>
        bossPokemon = 1,
        /// <summary>
        /// npc对战
        /// </summary>
        npc = 2,
    }

} 

