
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 副本类型
    /// </summary>
    public enum map_Type
    {
        /// <summary>
        /// 经典
        /// </summary>
        classic = 0,
        /// <summary>
        /// 无尽
        /// </summary>
        Endless = 1,
    }

} 

