
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// NPC枚举
    /// </summary>
    public enum npc
    {
        /// <summary>
        /// 甜菜
        /// </summary>
        beet = 0,
        /// <summary>
        /// 羊
        /// </summary>
        sheep = 1,
        /// <summary>
        /// 猴子
        /// </summary>
        monkey = 2,
        /// <summary>
        /// 绿羊
        /// </summary>
        Green_Sheep = 3,
    }

} 

