
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class plot : Luban.BeanBase
{
    public plot(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["npc_id"].IsNumber) { throw new SerializationException(); }  NpcId = _buf["npc_id"]; }
        { if(!_buf["text_time"].IsString) { throw new SerializationException(); }  TextTime = _buf["text_time"]; }
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
        { if(!_buf["next_id"].IsNumber) { throw new SerializationException(); }  NextId = _buf["next_id"]; }
    }

    public static plot Deserializeplot(JSONNode _buf)
    {
        return new plot(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 剧情备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对话npc
    /// </summary>
    public readonly int NpcId;
    /// <summary>
    /// 剧情文字
    /// </summary>
    public readonly string TextTime;
    /// <summary>
    /// 剧情文字持续时间
    /// </summary>
    public readonly float Time;
    /// <summary>
    /// 下个剧情id
    /// </summary>
    public readonly int NextId;
   
    public const int __ID__ = 3443937;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "npcId:" + NpcId + ","
        + "textTime:" + TextTime + ","
        + "time:" + Time + ","
        + "nextId:" + NextId + ","
        + "}";
    }
}
}

