
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 宝可梦进化
/// </summary>
public sealed partial class PokemonEvolution : Luban.BeanBase
{
    public PokemonEvolution(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["pokemonID"].IsNumber) { throw new SerializationException(); }  PokemonID = _buf["pokemonID"]; }
    }

    public static PokemonEvolution DeserializePokemonEvolution(JSONNode _buf)
    {
        return new PokemonEvolution(_buf);
    }

    /// <summary>
    /// 进化等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 目标ID
    /// </summary>
    public readonly int PokemonID;
   
    public const int __ID__ = 1232831496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "pokemonID:" + PokemonID + ","
        + "}";
    }
}
}

