
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 宝可梦属性
    /// </summary>
    public enum pokemon_Type1
    {
        /// <summary>
        /// 一般
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 1,
        /// <summary>
        /// 水
        /// </summary>
        Water = 2,
        /// <summary>
        /// 草
        /// </summary>
        Grass = 3,
        /// <summary>
        /// 电
        /// </summary>
        Electric = 4,
        /// <summary>
        /// 冰
        /// </summary>
        Ice = 5,
        /// <summary>
        /// 虫
        /// </summary>
        Bug = 6,
        /// <summary>
        /// 飞行
        /// </summary>
        Flying = 7,
        /// <summary>
        /// 地面
        /// </summary>
        Ground = 8,
        /// <summary>
        /// 岩石
        /// </summary>
        Rock = 9,
        /// <summary>
        /// 格斗
        /// </summary>
        Fighting = 10,
        /// <summary>
        /// 超能力
        /// </summary>
        Psychic = 11,
        /// <summary>
        /// 幽灵
        /// </summary>
        Ghost = 12,
        /// <summary>
        /// 毒
        /// </summary>
        Poison = 13,
        /// <summary>
        /// 恶
        /// </summary>
        Dark = 14,
        /// <summary>
        /// 钢
        /// </summary>
        Steel = 15,
        /// <summary>
        /// 龙
        /// </summary>
        Dragon = 16,
        /// <summary>
        /// 妖精
        /// </summary>
        Fairy = 17,
    }

} 

