
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class pokemonMove : Luban.BeanBase
{
    public pokemonMove(JSONNode _buf) 
    {
        { if(!_buf["pokemonId"].IsNumber) { throw new SerializationException(); }  PokemonId = _buf["pokemonId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["lowSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } LowSkill = new System.Collections.Generic.List<PokemonAISkill>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { PokemonAISkill __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.PokemonAISkill.DeserializePokemonAISkill(__e0);  }  LowSkill.Add(__v0); }   }
        { var __json0 = _buf["mediumSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } MediumSkill = new System.Collections.Generic.List<PokemonAISkill>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { PokemonAISkill __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.PokemonAISkill.DeserializePokemonAISkill(__e0);  }  MediumSkill.Add(__v0); }   }
        { var __json0 = _buf["highSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } HighSkill = new System.Collections.Generic.List<PokemonAISkill>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { PokemonAISkill __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.PokemonAISkill.DeserializePokemonAISkill(__e0);  }  HighSkill.Add(__v0); }   }
    }

    public static pokemonMove DeserializepokemonMove(JSONNode _buf)
    {
        return new pokemonMove(_buf);
    }

    /// <summary>
    /// 宝可梦id
    /// </summary>
    public readonly int PokemonId;
    /// <summary>
    /// ##宝可梦名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// lowSkill
    /// </summary>
    public readonly System.Collections.Generic.List<PokemonAISkill> LowSkill;
    /// <summary>
    /// mediumSkill
    /// </summary>
    public readonly System.Collections.Generic.List<PokemonAISkill> MediumSkill;
    /// <summary>
    /// highSkill
    /// </summary>
    public readonly System.Collections.Generic.List<PokemonAISkill> HighSkill;
   
    public const int __ID__ = 1308314436;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LowSkill) { _e?.ResolveRef(tables); }
        foreach (var _e in MediumSkill) { _e?.ResolveRef(tables); }
        foreach (var _e in HighSkill) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "pokemonId:" + PokemonId + ","
        + "name:" + Name + ","
        + "lowSkill:" + Luban.StringUtil.CollectionToString(LowSkill) + ","
        + "mediumSkill:" + Luban.StringUtil.CollectionToString(MediumSkill) + ","
        + "highSkill:" + Luban.StringUtil.CollectionToString(HighSkill) + ","
        + "}";
    }
}
}

