
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class pokemon : Luban.BeanBase
{
    public pokemon(JSONNode _buf) 
    {
        { if(!_buf["pokemonId"].IsNumber) { throw new SerializationException(); }  PokemonId = _buf["pokemonId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["image"].IsString) { throw new SerializationException(); }  Image = _buf["image"]; }
        { if(!_buf["shiny_Image"].IsString) { throw new SerializationException(); }  ShinyImage = _buf["shiny_Image"]; }
        { if(!_buf["pokemon_Type1"].IsString) { throw new SerializationException(); }  PokemonType1 = _buf["pokemon_Type1"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["defense"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["sp_attack"].IsNumber) { throw new SerializationException(); }  SpAttack = _buf["sp_attack"]; }
        { if(!_buf["sp_defense"].IsNumber) { throw new SerializationException(); }  SpDefense = _buf["sp_defense"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["capture_rate"].IsNumber) { throw new SerializationException(); }  CaptureRate = _buf["capture_rate"]; }
        { if(!_buf["base_happiness"].IsString) { throw new SerializationException(); }  BaseHappiness = _buf["base_happiness"]; }
        { if(!_buf["experience_growth"].IsNumber) { throw new SerializationException(); }  ExperienceGrowth = _buf["experience_growth"]; }
        { if(!_buf["evolution"].IsObject) { throw new SerializationException(); }  Evolution = global::cfg.PokemonEvolution.DeserializePokemonEvolution(_buf["evolution"]);  }
    }

    public static pokemon Deserializepokemon(JSONNode _buf)
    {
        return new pokemon(_buf);
    }

    /// <summary>
    /// 宝可梦id
    /// </summary>
    public readonly int PokemonId;
    /// <summary>
    /// 宝可梦名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 宝可梦图片
    /// </summary>
    public readonly string Image;
    /// <summary>
    /// 闪光图片
    /// </summary>
    public readonly string ShinyImage;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly string PokemonType1;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 特攻
    /// </summary>
    public readonly int SpAttack;
    /// <summary>
    /// 特防
    /// </summary>
    public readonly int SpDefense;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 捕获率
    /// </summary>
    public readonly int CaptureRate;
    /// <summary>
    /// 幸福度 重量
    /// </summary>
    public readonly string BaseHappiness;
    /// <summary>
    /// 升级速度
    /// </summary>
    public readonly int ExperienceGrowth;
    /// <summary>
    /// 进化条件
    /// </summary>
    public readonly PokemonEvolution Evolution;
   
    public const int __ID__ = -399033133;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Evolution?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "pokemonId:" + PokemonId + ","
        + "name:" + Name + ","
        + "image:" + Image + ","
        + "shinyImage:" + ShinyImage + ","
        + "pokemonType1:" + PokemonType1 + ","
        + "attack:" + Attack + ","
        + "defense:" + Defense + ","
        + "hp:" + Hp + ","
        + "spAttack:" + SpAttack + ","
        + "spDefense:" + SpDefense + ","
        + "speed:" + Speed + ","
        + "captureRate:" + CaptureRate + ","
        + "baseHappiness:" + BaseHappiness + ","
        + "experienceGrowth:" + ExperienceGrowth + ","
        + "evolution:" + Evolution + ","
        + "}";
    }
}
}

