
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// AI宝可梦Skill选择
/// </summary>
public sealed partial class PokemonAISkill : Luban.BeanBase
{
    public PokemonAISkill(JSONNode _buf) 
    {
        { if(!_buf["skillID"].IsNumber) { throw new SerializationException(); }  SkillID = _buf["skillID"]; }
        { if(!_buf["probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["probability"]; }
    }

    public static PokemonAISkill DeserializePokemonAISkill(JSONNode _buf)
    {
        return new PokemonAISkill(_buf);
    }

    /// <summary>
    /// 技能Id
    /// </summary>
    public readonly int SkillID;
    /// <summary>
    /// 释放概率
    /// </summary>
    public readonly int Probability;
   
    public const int __ID__ = -719931658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "skillID:" + SkillID + ","
        + "probability:" + Probability + ","
        + "}";
    }
}
}

