
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 品质枚举
    /// </summary>
    public enum quality
    {
        /// <summary>
        /// 白品质
        /// </summary>
        white = 0,
        /// <summary>
        /// 绿品质
        /// </summary>
        green = 1,
        /// <summary>
        /// 蓝品质
        /// </summary>
        blue = 2,
        /// <summary>
        /// 紫品质
        /// </summary>
        purple = 3,
        /// <summary>
        /// 橙品质
        /// </summary>
        orange = 4,
        /// <summary>
        /// 红品质
        /// </summary>
        red = 5,
    }

} 

