
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Config.Item Item {get; }
    public Config.Shop Shop {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Item = new Config.Item(loader("config_item"));
        Shop = new Config.Shop(loader("config_shop"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Item.ResolveRef(this);
        Shop.ResolveRef(this);
    }
}

}
