
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public test.TestDefine TestDefine {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TestDefine = new test.TestDefine(loader("test_testdefine"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TestDefine.ResolveRef(this);
    }
}

}
