
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbGlobal TbGlobal {get; }
    public TbItemNew TbItemNew {get; }
    public TBItemCombine TBItemCombine {get; }
    public TbPlot TbPlot {get; }
    public TbTask TbTask {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGlobal = new TbGlobal(loader("tbglobal"));
        TbItemNew = new TbItemNew(loader("tbitemnew"));
        TBItemCombine = new TBItemCombine(loader("tbitemcombine"));
        TbPlot = new TbPlot(loader("tbplot"));
        TbTask = new TbTask(loader("tbtask"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobal.ResolveRef(this);
        TbItemNew.ResolveRef(this);
        TBItemCombine.ResolveRef(this);
        TbPlot.ResolveRef(this);
        TbTask.ResolveRef(this);
    }
}

}
