
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class task : Luban.BeanBase
{
    public task(JSONNode _buf) 
    {
        { if(!_buf["goalId"].IsNumber) { throw new SerializationException(); }  GoalId = _buf["goalId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["npc"].IsNumber) { throw new SerializationException(); }  Npc = _buf["npc"]; }
        { if(!_buf["goalCount"].IsString) { throw new SerializationException(); }  GoalCount = _buf["goalCount"]; }
        { if(!_buf["reward"].IsString) { throw new SerializationException(); }  Reward = _buf["reward"]; }
        { var __json0 = _buf["accept_dialog"]; if(!__json0.IsArray) { throw new SerializationException(); } AcceptDialog = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AcceptDialog.Add(__v0); }   }
        { var __json0 = _buf["progress_hint"]; if(!__json0.IsArray) { throw new SerializationException(); } ProgressHint = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ProgressHint.Add(__v0); }   }
        { var __json0 = _buf["complete_dialog"]; if(!__json0.IsArray) { throw new SerializationException(); } CompleteDialog = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CompleteDialog.Add(__v0); }   }
        { if(!_buf["next_goalId"].IsNumber) { throw new SerializationException(); }  NextGoalId = _buf["next_goalId"]; }
        { if(!_buf["npc_quest_bubble"].IsString) { throw new SerializationException(); }  NpcQuestBubble = _buf["npc_quest_bubble"]; }
    }

    public static task Deserializetask(JSONNode _buf)
    {
        return new task(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int GoalId;
    /// <summary>
    /// 任务名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// npcid
    /// </summary>
    public readonly int Npc;
    /// <summary>
    /// 任务要求
    /// </summary>
    public readonly string GoalCount;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly string Reward;
    /// <summary>
    /// 接取时剧情id
    /// </summary>
    public readonly System.Collections.Generic.List<int> AcceptDialog;
    /// <summary>
    /// 进行时剧情id
    /// </summary>
    public readonly System.Collections.Generic.List<int> ProgressHint;
    /// <summary>
    /// 完成时剧情id
    /// </summary>
    public readonly System.Collections.Generic.List<int> CompleteDialog;
    /// <summary>
    /// 下一个任务id
    /// </summary>
    public readonly int NextGoalId;
    /// <summary>
    /// 任务气泡
    /// </summary>
    public readonly string NpcQuestBubble;
   
    public const int __ID__ = 3552645;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "goalId:" + GoalId + ","
        + "name:" + Name + ","
        + "npc:" + Npc + ","
        + "goalCount:" + GoalCount + ","
        + "reward:" + Reward + ","
        + "acceptDialog:" + Luban.StringUtil.CollectionToString(AcceptDialog) + ","
        + "progressHint:" + Luban.StringUtil.CollectionToString(ProgressHint) + ","
        + "completeDialog:" + Luban.StringUtil.CollectionToString(CompleteDialog) + ","
        + "nextGoalId:" + NextGoalId + ","
        + "npcQuestBubble:" + NpcQuestBubble + ","
        + "}";
    }
}
}

