
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHouse
{
    private readonly System.Collections.Generic.Dictionary<int, house> _dataMap;
    private readonly System.Collections.Generic.List<house> _dataList;
    
    public TbHouse(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, house>(count);
        _dataList = new System.Collections.Generic.List<house>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            house _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.house.Deserializehouse(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, house> DataMap => _dataMap;
    public System.Collections.Generic.List<house> DataList => _dataList;

    public house GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public house Get(int key) => _dataMap[key];
    public house this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

