
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBItemCombine
{
    private readonly System.Collections.Generic.Dictionary<int, ItemCombine> _dataMap;
    private readonly System.Collections.Generic.List<ItemCombine> _dataList;
    
    public TBItemCombine(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemCombine>(count);
        _dataList = new System.Collections.Generic.List<ItemCombine>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemCombine _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ItemCombine.DeserializeItemCombine(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemCombine> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemCombine> DataList => _dataList;

    public ItemCombine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemCombine Get(int key) => _dataMap[key];
    public ItemCombine this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

