
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbItemNew
{
    private readonly System.Collections.Generic.Dictionary<int, ItemNew> _dataMap;
    private readonly System.Collections.Generic.List<ItemNew> _dataList;
    
    public TbItemNew(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemNew>(count);
        _dataList = new System.Collections.Generic.List<ItemNew>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemNew _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ItemNew.DeserializeItemNew(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemNew> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemNew> DataList => _dataList;

    public ItemNew GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemNew Get(int key) => _dataMap[key];
    public ItemNew this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

