
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, item> _dataMap;
    private readonly System.Collections.Generic.List<item> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, item>(count);
        _dataList = new System.Collections.Generic.List<item>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.item.Deserializeitem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item> DataMap => _dataMap;
    public System.Collections.Generic.List<item> DataList => _dataList;

    public item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public item Get(int key) => _dataMap[key];
    public item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

