
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbMap
{
    private readonly System.Collections.Generic.Dictionary<int, map> _dataMap;
    private readonly System.Collections.Generic.List<map> _dataList;
    
    public TbMap(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, map>(count);
        _dataList = new System.Collections.Generic.List<map>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            map _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.map.Deserializemap(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.MapId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, map> DataMap => _dataMap;
    public System.Collections.Generic.List<map> DataList => _dataList;

    public map GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public map Get(int key) => _dataMap[key];
    public map this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

