
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbMove
{
    private readonly System.Collections.Generic.Dictionary<int, move> _dataMap;
    private readonly System.Collections.Generic.List<move> _dataList;
    
    public TbMove(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, move>(count);
        _dataList = new System.Collections.Generic.List<move>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            move _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.move.Deserializemove(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.MoveId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, move> DataMap => _dataMap;
    public System.Collections.Generic.List<move> DataList => _dataList;

    public move GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public move Get(int key) => _dataMap[key];
    public move this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

