
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPlot
{
    private readonly System.Collections.Generic.Dictionary<int, plot> _dataMap;
    private readonly System.Collections.Generic.List<plot> _dataList;
    
    public TbPlot(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, plot>(count);
        _dataList = new System.Collections.Generic.List<plot>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            plot _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.plot.Deserializeplot(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, plot> DataMap => _dataMap;
    public System.Collections.Generic.List<plot> DataList => _dataList;

    public plot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public plot Get(int key) => _dataMap[key];
    public plot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

