
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPokemonMove
{
    private readonly System.Collections.Generic.Dictionary<int, pokemonMove> _dataMap;
    private readonly System.Collections.Generic.List<pokemonMove> _dataList;
    
    public TbPokemonMove(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, pokemonMove>(count);
        _dataList = new System.Collections.Generic.List<pokemonMove>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            pokemonMove _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.pokemonMove.DeserializepokemonMove(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PokemonId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, pokemonMove> DataMap => _dataMap;
    public System.Collections.Generic.List<pokemonMove> DataList => _dataList;

    public pokemonMove GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public pokemonMove Get(int key) => _dataMap[key];
    public pokemonMove this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

