
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPokemon
{
    private readonly System.Collections.Generic.Dictionary<int, pokemon> _dataMap;
    private readonly System.Collections.Generic.List<pokemon> _dataList;
    
    public TbPokemon(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, pokemon>(count);
        _dataList = new System.Collections.Generic.List<pokemon>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            pokemon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.pokemon.Deserializepokemon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PokemonId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, pokemon> DataMap => _dataMap;
    public System.Collections.Generic.List<pokemon> DataList => _dataList;

    public pokemon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public pokemon Get(int key) => _dataMap[key];
    public pokemon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

