
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTask
{
    private readonly System.Collections.Generic.Dictionary<int, task> _dataMap;
    private readonly System.Collections.Generic.List<task> _dataList;
    
    public TbTask(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, task>(count);
        _dataList = new System.Collections.Generic.List<task>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            task _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.task.Deserializetask(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GoalId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, task> DataMap => _dataMap;
    public System.Collections.Generic.List<task> DataList => _dataList;

    public task GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public task Get(int key) => _dataMap[key];
    public task this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

