
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTypeChart
{
    private readonly System.Collections.Generic.Dictionary<int, typeChart> _dataMap;
    private readonly System.Collections.Generic.List<typeChart> _dataList;
    
    public TbTypeChart(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, typeChart>(count);
        _dataList = new System.Collections.Generic.List<typeChart>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            typeChart _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.typeChart.DeserializetypeChart(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, typeChart> DataMap => _dataMap;
    public System.Collections.Generic.List<typeChart> DataList => _dataList;

    public typeChart GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public typeChart Get(int key) => _dataMap[key];
    public typeChart this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

